# Generated by Django 3.2.6 on 2021-08-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Будьте добры ввести ваше имя. /n ввод строго на английском.'),
        ),
    ]
